// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"gotraining3/internal/week3/biz"
	"gotraining3/internal/week3/data"
	"gotraining3/internal/week3/pkg"
	"gotraining3/internal/week3/service"
)

// Injectors from wire.go:

func InitPictureService() *service.PictureService {
	database := pkg.NewDB()
	pictureRepo := data.NewPictureRepo(database)
	pictrueUsecase := biz.NewPictrueUsecase(pictureRepo)
	pictureService := service.NewPictrueService(pictrueUsecase)
	return pictureService
}
