// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: homework3.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the Picture's name.
type PictureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PictureRequest) Reset() {
	*x = PictureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homework3_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureRequest) ProtoMessage() {}

func (x *PictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homework3_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureRequest.ProtoReflect.Descriptor instead.
func (*PictureRequest) Descriptor() ([]byte, []int) {
	return file_homework3_proto_rawDescGZIP(), []int{0}
}

func (x *PictureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type PictureReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PictureReply) Reset() {
	*x = PictureReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homework3_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PictureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureReply) ProtoMessage() {}

func (x *PictureReply) ProtoReflect() protoreflect.Message {
	mi := &file_homework3_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureReply.ProtoReflect.Descriptor instead.
func (*PictureReply) Descriptor() ([]byte, []int) {
	return file_homework3_proto_rawDescGZIP(), []int{1}
}

func (x *PictureReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_homework3_proto protoreflect.FileDescriptor

var file_homework3_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x24, 0x0a, 0x0e, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x28, 0x0a, 0x0c, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x54, 0x0a, 0x0d, 0x48,
	0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x57, 0x65, 0x65, 0x6b, 0x33, 0x12, 0x43, 0x0a, 0x0d,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x2e,
	0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_homework3_proto_rawDescOnce sync.Once
	file_homework3_proto_rawDescData = file_homework3_proto_rawDesc
)

func file_homework3_proto_rawDescGZIP() []byte {
	file_homework3_proto_rawDescOnce.Do(func() {
		file_homework3_proto_rawDescData = protoimpl.X.CompressGZIP(file_homework3_proto_rawDescData)
	})
	return file_homework3_proto_rawDescData
}

var file_homework3_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_homework3_proto_goTypes = []interface{}{
	(*PictureRequest)(nil), // 0: homework.PictureRequest
	(*PictureReply)(nil),   // 1: homework.PictureReply
}
var file_homework3_proto_depIdxs = []int32{
	0, // 0: homework.HomeworkWeek3.ModifyPicture:input_type -> homework.PictureRequest
	1, // 1: homework.HomeworkWeek3.ModifyPicture:output_type -> homework.PictureReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_homework3_proto_init() }
func file_homework3_proto_init() {
	if File_homework3_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_homework3_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PictureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homework3_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PictureReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_homework3_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_homework3_proto_goTypes,
		DependencyIndexes: file_homework3_proto_depIdxs,
		MessageInfos:      file_homework3_proto_msgTypes,
	}.Build()
	File_homework3_proto = out.File
	file_homework3_proto_rawDesc = nil
	file_homework3_proto_goTypes = nil
	file_homework3_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HomeworkWeek3Client is the client API for HomeworkWeek3 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HomeworkWeek3Client interface {
	// Modify a picture
	ModifyPicture(ctx context.Context, in *PictureRequest, opts ...grpc.CallOption) (*PictureReply, error)
}

type homeworkWeek3Client struct {
	cc grpc.ClientConnInterface
}

func NewHomeworkWeek3Client(cc grpc.ClientConnInterface) HomeworkWeek3Client {
	return &homeworkWeek3Client{cc}
}

func (c *homeworkWeek3Client) ModifyPicture(ctx context.Context, in *PictureRequest, opts ...grpc.CallOption) (*PictureReply, error) {
	out := new(PictureReply)
	err := c.cc.Invoke(ctx, "/homework.HomeworkWeek3/ModifyPicture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomeworkWeek3Server is the server API for HomeworkWeek3 service.
type HomeworkWeek3Server interface {
	// Modify a picture
	ModifyPicture(context.Context, *PictureRequest) (*PictureReply, error)
}

// UnimplementedHomeworkWeek3Server can be embedded to have forward compatible implementations.
type UnimplementedHomeworkWeek3Server struct {
}

func (*UnimplementedHomeworkWeek3Server) ModifyPicture(context.Context, *PictureRequest) (*PictureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyPicture not implemented")
}

func RegisterHomeworkWeek3Server(s *grpc.Server, srv HomeworkWeek3Server) {
	s.RegisterService(&_HomeworkWeek3_serviceDesc, srv)
}

func _HomeworkWeek3_ModifyPicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeworkWeek3Server).ModifyPicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/homework.HomeworkWeek3/ModifyPicture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeworkWeek3Server).ModifyPicture(ctx, req.(*PictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HomeworkWeek3_serviceDesc = grpc.ServiceDesc{
	ServiceName: "homework.HomeworkWeek3",
	HandlerType: (*HomeworkWeek3Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModifyPicture",
			Handler:    _HomeworkWeek3_ModifyPicture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "homework3.proto",
}
